name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "b1d2e4f3f1cf46c5a404f19b8484e27e"				#KV数据库id
